Repository reliatec-gmbh/LibreClinica, pull requests merged in 2020-11, with the labels that each got.

#177 Issue 176
  web/src/main/webapp/WEB-INF/jsp/include/sideInfo.jsp
Labels: maintenance

#178 issue #126
  web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
Labels: bug

#190 Issue 151
  docs/instructions/install_lc-1.0_official.md
  docs/instructions/migrate_oc_to_lc.md
Labels: documentation

#201 Added tests T011, T012, T013 and T015
  docs/tests/index.md
  docs/tests/t011.md
  docs/tests/t012.md
  docs/tests/t013.md
  docs/tests/t014.md
  docs/tests/t015.md
Labels: testing
