Repository reliatec-gmbh/LibreClinica, pull requests merged in 2020-02, with the labels that each got.

#147 issue #141: remove references to OpenClinica from CRF template
  .gitignore
  core/src/main/resources/properties/CRF_Template_lc_v1.0.xls
  web/src/main/java/org/akaza/openclinica/control/admin/DownloadVersionSpreadSheetServlet.java
Labels: maintenance

#117 Fix for deleting an Event CRF results in oops page
  core/src/main/java/org/akaza/openclinica/dao/hibernate/DynamicsItemFormMetadataDao.java
  core/src/main/java/org/akaza/openclinica/dao/hibernate/DynamicsItemGroupMetadataDao.java
  core/src/main/java/org/akaza/openclinica/dao/hibernate/RuleActionRunLogDao.java
Labels: bug

#121 added test T014
  docs/index.md
  docs/sidebar.md
  docs/tests/t014.md
Labels: testing

#130 Fix creating an import job results in oops
  web/src/main/java/org/akaza/openclinica/control/admin/CreateJobImportServlet.java
  web/src/main/java/org/akaza/openclinica/control/admin/UpdateJobImportServlet.java
  web/src/main/java/org/akaza/openclinica/controller/ScheduledJobController.java
  web/src/main/java/org/akaza/openclinica/web/job/TriggerService.java
Labels: bug

#133 Fix for running a rule in a study without item data results in an oops
  core/src/main/java/org/akaza/openclinica/logic/rulerunner/RuleSetBulkRuleRunner.java
  core/src/main/java/org/akaza/openclinica/service/rule/RuleSetService.java
Labels: bug

#138 Altering qrtz blob columns to bytea to fix the new DB initialisation
  core/src/main/resources/migration/lc-1.0.0/qrtz_blob_to_bytea.xml
  core/src/main/resources/migration/lc-1.0.0/release.xml
Labels: bug

#150 load ehcache.xml even if the CacheManager already has a configuration…
  core/src/main/java/org/akaza/openclinica/dao/core/SQLFactory.java
  core/src/main/resources/org/akaza/openclinica/ehcache.xml
Labels: bug

#63 issue 61: Person ID in Subject Matrix
  core/src/main/java/org/akaza/openclinica/dao/managestudy/FindSubjectsFilter.java
  core/src/main/java/org/akaza/openclinica/dao/managestudy/FindSubjectsSort.java
  web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
  web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableToolbar.java
  web/src/main/webapp/WEB-INF/jsp/managestudy/showStudySubjectRow.jsp
Labels: enhancement

#163 Fix the trigger for rescheduling of job to use the updated startDate
  web/src/main/java/org/akaza/openclinica/controller/ScheduledJobController.java
Labels: bug

#165 set 'hibernate.allow_update_outside_transaction' to true
  core/src/main/resources/org/akaza/openclinica/applicationContext-core-hibernate.xml
Labels: bug
