Repository reliatec-gmbh/LibreClinica, pull requests merged in 2021-01, with the labels that each got.

#204 Extend install manual with LDAP configuration details
  docs/instructions/install_lc-1.0_official.md
Labels: documentation

#199 Refactor the process of adding new LDAP users to not use iframe
  core/src/main/java/org/akaza/openclinica/service/user/LdapUserService.java
  web/src/main/java/org/akaza/openclinica/controller/user/LdapUserController.java
  web/src/main/webapp/WEB-INF/jsp/admin/createuseraccount.jsp
  web/src/main/webapp/WEB-INF/jsp/admin/listLdapUsers.jsp
  web/src/main/webapp/WEB-INF/jsp/listLdapUsers.jsp
Labels: bug

#219 Test for user creation - LDAP: T003-08
  docs/tests/t003.md
Labels: documentation, testing

#182 Study side info cleanup
  core/src/main/resources/org/akaza/openclinica/i18n/words.properties
  web/src/main/webapp/WEB-INF/jsp/include/studySideInfo.jsp
Labels: bug
