Repository reliatec-gmbh/LibreClinica, pull requests merged in 2022-08, with the labels that each got.

#342 Lc develop admin manual
  .gitignore
  core/src/main/filters/datainfo.properties
  core/src/main/java/org/akaza/openclinica/dao/core/CoreResources.java
  core/src/main/resources/org/akaza/openclinica/applicationContext-core-service.xml
  core/src/test/resources/datainfo.properties
  docs/.gitignore
  docs/manuals/administrator-manual.md
  docs/manuals/administrator-manual_images/administer-users-letter.png
  docs/manuals/administrator-manual_images/change-user-profile-application.png
  docs/manuals/administrator-manual_images/login_mail.png
  docs/manuals/administrator-manual_images/update_study_details.png
  docs/manuals/administrator-manual_images/user-account-letter.png
  docs/manuals/index.md
  docs/manuals/investigator-manual.pdf
  docs/manuals/monitor-manual.md
  docs/manuals/monitor-manual.pdf
  docs/manuals/package.json
  docs/manuals/sidebar.md
  docs/pom.xml
  pom.xml
  web/pom.xml
  web/src/main/filters/datainfo.properties
  web/src/main/resources/datainfo.properties
  web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp
Labels: documentation

#345 Update the PG JDBC driver version
  pom.xml
Labels: maintenance

#347 Fix typo in t001 related to 2FA test
  docs/tests/t001.md
Labels: documentation

#348 Fix missing Janino library needed by Logback
  core/pom.xml
  pom.xml
Labels: bug

#350 #349
  core/src/main/java/org/akaza/openclinica/service/otp/TwoFactorService.java
  core/src/test/java/org/akaza/openclinica/service/otp/TwoFactorServiceTest.java
  docs/tests/t003.md
  pom.xml
  web/pom.xml
Labels: enhancement
